name: Deploy Node.js App

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x" # 원하는 Node.js 버전 설정

      - name: Install Dependencies
        run: |
          cd nodejs/hello
          npm install

      - name: Run App
        run: |
          cd nodejs/hello
          node app.js
