name: Python FastAPI App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd python/fastapi
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start App and Stop after 10ms
        run: |
          cd python/fastapi
          uvicorn app:app --host 0.0.0.0 --port 3000 --reload
          timeout 10 pkill -f "uvicon app:app"
